Controllers films users
AFilatkov/java-filmorate pull request #6
Opened 2023-07-30 14:31 UTC by AFilatkov

2023-07-31 18:10 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@RequestMapping("/users")
эти две аннотации поменяй местами, обычно располагают так

2023-07-31 18:10 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private HashMap<Integer, User> users = new HashMap<>();
Разделяй статичные и нестатичные переменные отступом

2023-07-31 18:14 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return user;
Если пользователь не валиден, может его вообще не надо возвращать в ответе?

2023-07-31 18:15 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return user;
Например кинуть исключение

2023-07-31 18:16 UTC, PolnySkvorets commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Много отступов, проверь выравнивание

2023-07-31 18:17 UTC, PolnySkvorets requested changes
Привет! Посмотри замечания: немного по-разному написаны валидации, немного форматирование подправить, в остальном - хорошо

2023-08-01 16:27 UTC, AFilatkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return user;
Там сам метод validateUser выбрасывает исключение, поэтому я его не добавлял, а что вернуть в методе createUser, если появится исключение в validateUser, нам еще не объясняли

2023-08-01 16:29 UTC, AFilatkov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Отступ 4 пробела, как и во всем проекте, я проверил

2023-08-01 20:27 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return film;
В обоих случаях возвращается film . Можно оставить только блок if. else - убрать. и после if в конце метода сделать return ilm

2023-08-01 20:42 UTC, PolnySkvorets reviewed
Посмотри последнее замечание. Немного неоптимально метод написан

2023-08-03 14:41 UTC, PolnySkvorets approved these changes
Всё хорошо

2023-08-05 17:56 UTC, merged